openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
# servers:
#   - url: http://api.example.com/v1
#     description: Optional server description, e.g. Main (production) server
paths:
  /:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
      x-code-samples:
        - lang: 'HTTP'
          source: |
            endpoint: 'http://www.sampleapi.com/'
            Example:
                Headers:
                    “email” : “mary@lamb.com“
                    “password” : “Pass@1234”

            The above API authenticates user with email `mary@lamb.comand passwordPass@1234`.
        - lang: GraphQL
          source: |
            {
                users{
                    email
                }
            }